### ISSUE TITLE
About the ablation study after removing attribute information

### ISSUE THREAD

**Issue by Bruce-Y12** [OreOZhao/TEA#2]
I directly remove the  attribute information as follows:：
` # trainer.data_prepare(eid2attr_tids1, eid2attr_tids2, fs1, fs2,  eid2nei_tids1, eid2nei_tids2)
        trainer.data_prepare(eid2nei_tids1, eid2nei_tids2, fs1, fs2, None, None)
`
I got hit@1 Only 69.25, there is still a difference compared to 81.5. Is there a problem with the way of removing attribute information?

**Comment by OreOZhao** [comment]
Thank you for your attention to our work.

I think that 69.25 maybe the results before reranking. It would be helpful if you provide more details, such as the log of evaluation process : )
