### ISSUE TITLE
Results on SRPRS(DBP-WD) is lower

### ISSUE THREAD

**Issue by Arlannn1** [OreOZhao/TEA#3]
Hello, first thank you for sharing the code! It was so glad to see your works.

I noticed that there is no experiment about SRPRS(DBP-WD) in your paper.

When I run your model on this task, the result is abnormal, only about 80, while DBP-YG looks normal.

Can you get a normal result? If so, please tell me what the problem is.

I hope I can get your help and look forward to your reply very sincerely！

**Comment by OreOZhao** [comment]
Thank you for your attention to our work!

We did not run TEA on SRPRS(DBP-WD) or SRPRS (DBP-YG). But I think it is normal that directly running TEA on DBP-WD would not perform well. The reason could be that WD KG in SRPRS does not contain entity names but entity identifiers, which is challenging for PLMs for capturing semantic information. We also mention the problem concerning entity names in Section Limitation in our paper.

For reference, following SDEA (Sec. V.A) and replace the identifier with crawled entity names may resolve the problem. You could try it if you are interested. I will also work on the issue in the future too.  : )
