### ISSUE TITLE
error when preprocessing DBP15K dataset

### ISSUE THREAD

**Issue by chensyCN** [OreOZhao/TEA#4]
Hello, I am reproducing your experiments using this code. When i run the provided script to preprocess DBP15K, an error occurred:

```bash
Traceback (most recent call last):
  File "DBPPreprocess.py", line 53, in <module>
    folds = os.listdir('mapping')
FileNotFoundError: [Errno 2] No such file or directory: 'mapping'
```

Can you help with this issue, thanks a lot!

**Comment by OreOZhao** [comment]
Thank you for your attention to our work!

Sorry for the mistake during code organization. 
You could directly comment or delete the two lines concerning `folds` and the rest should work well.
